= Build Tool Integration
:jbake-type: page
:jbake-tags: documentation
:jbake-status: published
:idprefix:

== Maven Plugin

The JBake Maven plugin allows you to run JBake from your http://maven.apache.org[Maven] build.
It is available from the Maven Central repository using the following coordinates:

[source,xml]
----
<dependency>
    <groupId>org.jbake</groupId>
    <artifactId>jbake-maven-plugin</artifactId>
    <version>${jbakeVersion}</version>
</dependency>
----

The plugin was originally created by https://github.com/aldrinleal[Aldrin Leal].

=== Usage (maven plugin)

To use JBake Maven Plugin, add the plugin in your `pom.xml`:

----
<build>
    <plugins>
        <plugin>
            <groupId>org.jbake</groupId>
            <artifactId>jbake-maven-plugin</artifactId>
            <version>${jbakeVersion}</version>
            <configuration>
                <inputDirectory>${project.basedir}</inputDirectory>
                <outputDirectory>${project.build.directory}/website</outputDirectory>
            </configuration>
            <executions>
                <execution>
                    <phase>generate-resources</phase>
                    <goals>
                        <goal>generate</goal>
                    </goals>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
----

This configuration expects this directory structure:

----
my-project/
    assets/
        my-logo.png
        ...
    content/
        my-page.adoc
        ...
    templates/
        my-template.ftl
        ...
    jbake.properties
    pom.xml
----

Run `mvn generate-resources` and open `my-project/target/website/index.html` in a browser to see the result.

=== Goals (maven plugin)

There are 4 goals provided by the maven plugin:

* `jbake:seed` - seeds your project/site with example content and templates
* `jbake:generate` - bakes your project/site
* `jbake:watch` - watches to changes and bakes your site whenever a change is detected
* `jbake:inline` - bakes, watches and serves out content on http://localhost:8820[http://localhost:8820]

Get more details on each goal by running the help goal:

----
$ mvn jbake:help -Ddetail # -DgoalName=[seed|generate|watch|inline]
----

== Gradle Plugin

There is a http://gradle.org/[Gradle] plugin that allows you to run JBake from your Gradle build.

* https://plugins.gradle.org/plugin/org.jbake.site[Plugin Page on Gradle.org]
* https://github.com/jbake-org/jbake-gradle-plugin[Plugin on GitHub]
* https://bintray.com/jbake/maven/jbake-gradle-plugin[Plugin on Bintray]

The plugin was originally created by http://melix.github.io/blog/[Cédric Champeau].


== mill Plugin

There is a https://com-lihaoyi.github.io/mill/[mill] plugin that integrates site generation with JBake into mill.

* https://github.com/lefou/mill-jbake[Plugin on GitHub]

The plugin was developed and is maintained by https://github.com/lefou[Tobias Roeser].


== sbt Plugin

There is a https://www.scala-sbt.org/[sbt] plugin that integrates site generation with JBake into sbt.

* https://github.com/woq-blended/sbt-jbake[Plugin on GitHub]

The plugin was developed and is maintained by https://github.com/lefou[Tobias Roeser].


== SBuild Plugin

There is a http://sbuild.org/[SBuild] plugin that allows you to run JBake from your SBuild build.

* https://github.com/SBuild-org/sbuild-jbake[Plugin on GitHub]

The plugin is available from the Maven Central repository using the following coordinates:

[source,xml]
----
<dependency>
    <groupId>org.sbuild</groupId>
    <artifactId>org.sbuild.plugins.jbake</artifactId>
    <version>0.1.2</version>
</dependency>
----

The plugin was developed by https://github.com/lefou[Tobias Roeser].

