= JBake v2.7.0 release candidate available
Jonathan Bullock
2021-06-07
:jbake-type: post
:jbake-tags: community
:jbake-status: published
:category: news
:idprefix:

== JBake v2.7.0 release candidate available

We're getting close to the release of JBake v2.7.0, and given the scale of code changes that have been made recently we thought it was prudent to make a release candidate available.

So JBake v2.7.0-rc.7 is now available from https://github.com/jbake-org/jbake/releases[GitHub Releases]

We'd be really grateful if you could try this release candidate out against any JBake sites/projects you have. If you encounter any issues please https://github.com/jbake-org/jbake/issues[let us know] so we can address them prior to the final release of v2.7.0

=== Important changes

==== JBake Maven Plugin (v2.7.0-rc.7 or higher)

The JBake Maven plugin version is now aligns to the JBake version
and includes all optional JBake core dependencies.
Every JBake release now also includes a jbake-maven-plugin release.

This makes it easier to upgrade JBake: no need to align the dependencies any more.
It is now also easy to see which JBake version you're actually using.

Before in `pom.xml`:

----
      <plugin>
        <groupId>org.jbake</groupId>
        <artifactId>jbake-maven-plugin</artifactId>
        <version>0.3.5</version><!-- 0.3.5 uses JBake 2.6.7 -->
        ...
        <dependencies>
          <dependency>
            <groupId>org.asciidoctor</groupId>
            <artifactId>asciidoctorj</artifactId>
            <version>2.4.3</version><!-- Adjust when upgrading JBake -->
          </dependency>
          <dependency>
            <groupId>org.freemarker</groupId>
            <artifactId>freemarker</artifactId>
            <version>2.3.31</version><!-- Adjust when upgrading JBake  -->
          </dependency>
          ...
        </dependencies>
      </plugin>
----

After in `pom.xml`:

----
      <plugin>
        <groupId>org.jbake</groupId>
        <artifactId>jbake-maven-plugin</artifactId>
        <version>2.7.0</version><!-- Same as JBake version -->
        ...
        <!-- No need to maintain transitive dependencies -->
      </plugin>
----
