name: GitHub Pages deployment

on:
    push:
        branches:
            - master

jobs:
    build-deploy:
        runs-on: ubuntu-latest

        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-java@v3
              with:
                  java-version: 17
                  distribution: 'zulu'
                  cache: 'maven'

            - run: mvn -ntp -B clean generate-resources

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./target/website
                  cname: jbake.org
